apiVersion: v1
kind: ConfigMap
metadata:
  name: osd-cluster-metadata
  namespace: openshift-config
data:
  api.openshift.com_name: "{{ fromCDLabel \"api.openshift.com/name\" }}"
  api.openshift.com_product: "{{ fromCDLabel \"api.openshift.com/product\" }}"
  api.openshift.com_fedramp: "{{ fromCDLabel \"api.openshift.com/fedramp\" }}"
  api.openshift.com_sts: "{{ fromCDLabel \"api.openshift.com/sts\" }}"
  api.openshift.com_limited-support: "{{ fromCDLabel \"api.openshift.com/limited-support\" }}"
  api.openshift.com_private-link: "{{ fromCDLabel \"api.openshift.com/private-link\" }}"
  api.openshift.com_ccs: "{{ fromCDLabel \"api.openshift.com/ccs\" }}"
  api.openshift.com_channel-group: "{{ fromCDLabel \"api.openshift.com/channel-group\" }}"
  api.openshift.com_environment: "{{ fromCDLabel \"api.openshift.com/environment\" }}"
  hive.openshift.io_cluster-platform: "{{ fromCDLabel \"hive.openshift.io/cluster-platform\" }}"
  hive.openshift.io_cluster-region: "{{ fromCDLabel \"hive.openshift.io/cluster-region\" }}"
